# Docker Compose configuration for SearxNG Simple MCP Server
# Uses uv for Python dependency management

services:
  searxng-simple-mcp:
    image: ghcr.io/sacode/searxng-simple-mcp:latest
    # Uncomment below to build locally instead of using the published image
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: searxng-simple-mcp
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SEARXNG_MCP_SEARXNG_URL=https://searx.info
      - SEARXNG_MCP_TIMEOUT=10
      - SEARXNG_MCP_MAX_RESULTS=20
      - SEARXNG_MCP_LANGUAGE=all
      - SEARXNG_MCP_LOG_LEVEL=ERROR # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
      - TRANSPORT_PROTOCOL=sse # Transport protocol: stdio or sse
